/*
  Model for Collection (11 fields)
  Generated at 6/25/2026, 12:12:00 AM
  Powered by evolutility-models v.0.3.0 - https://github.com/evoluteur/evolutility-models
*/

import type { ModelDB } from "../types.ts";

export const collection = {
  id: "collection",
  title: "Collection",
  world: "designer",
  name: "collection",
  namePlural: "collections",
  pKey: "id",
  table: "evol_object_collec",
  titleField: "label",
  fields: [
    {
      id: "label",
      type: "text",
      label: "Label",
      maxLength: 200,
      inMany: true,
      column: "label",
      inSearch: true,
    },
    {
      id: "cid",
      type: "text",
      label: "Collection Id",
      required: true,
      maxLength: 50,
      inMany: true,
      column: "cid",
      inSearch: true,
    },
    {
      id: "position",
      type: "integer",
      label: "Position",
      inMany: true,
      column: "position",
    },
    {
      id: "table",
      type: "text",
      label: "DB Table name",
      required: true,
      maxLength: 63,
      inMany: true,
      column: "table",
      inSearch: true,
    },
    {
      id: "column",
      type: "text",
      label: "DB Column",
      required: true,
      maxLength: 63,
      inMany: true,
      column: "dbcolumn",
      inSearch: true,
    },
    {
      id: "object",
      type: "lov",
      label: "Object",
      object: "object",
      required: true,
      noCharts: true,
      lovIcon: false,
      inMany: true,
      column: "object_id",
      lovTable: "evol_object",
      lovColumn: "title",
      deleteTrigger: true,
    },
    {
      id: "fields",
      type: "json",
      label: "Fields",
      required: true,
      column: "fields",
    },
    {
      id: "help",
      type: "textmultiline",
      label: "help",
      maxLength: 500,
      column: "help",
    },
    {
      id: "header",
      type: "textmultiline",
      label: "Header",
      maxLength: 500,
      column: "header",
    },
    {
      id: "footer",
      type: "textmultiline",
      label: "Footer",
      maxLength: 500,
      column: "footer",
    },
    {
      id: "description",
      type: "textmultiline",
      label: "Description",
      maxLength: 250,
      column: "description",
      inSearch: true,
    },
  ],
  collections: [],
} satisfies ModelDB;
